### ISSUE TITLE
Relative URL is used instead of Greenhouse

### ISSUE THREAD

**Issue by dsspence** [tBaxter/DSCovery#2]
Cool project, thanks for putting this together.

It looks like the use of relative links are resulting in 404 pages, such as for the case of 540.co which uses Greenhouse.io for their jobs.

The link on the page resolves to https://dscovery.fly.dev/540/jobs/5961483003 

When the full URL should be https://boards.greenhouse.io/540/jobs/5961483003

**Comment by tBaxter** [comment]
Thank you... it actually has to do with how the importer constructs the job URL, but definitely a defect. Thanks for reporting!

**Comment by tBaxter** [comment]
Annnnnndddd... should be fixed now, for everyone using greenhouse.
